#!/bin/sh

export DOCKER_HOST=tcp://nas.np.dotnot.pl:2376
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH=~/.docker/nas.np.dotnot.pl/

container="postgres"

# build options for non-tty
if [ -t 0 ]; then
  # stdin to TTY -> interactive with TTY
  DOCKER_EXEC_OPTS="-it"
else
  # stdin to pipe / redirect -> stdin, no TTY
  DOCKER_EXEC_OPTS="-i"
fi

if [ $# -eq 0 ]; then
  /usr/bin/docker exec ${DOCKER_EXEC_OPTS} "${container}" psql -U postgres -d postgres
else
  /usr/bin/docker exec ${DOCKER_EXEC_OPTS} "${container}" psql -U postgres "$@"
fi

