#!/bin/bash

magnet() {
  echo "Magnet not supported" && return
  [[ "$1" =~ xt=urn:btih:([^&/]+) ]] || return
  hashh=${BASH_REMATCH[1]}
  if [[ "$1" =~ dn=([^&/]+) ]];then
    filename=${BASH_REMATCH[1]}
  else
    filename=$hashh
  fi
  echo "d10:magnet-uri${#1}:${1}e" > ~/downloads/meta-$filename.torrent
  echo "magnet, should be OK :)"
}

torrent() {
  url=$1
  tmpfile=`mktemp`

  wget -O $tmpfile "${url}" 2>/dev/null

  type=`file -b $tmpfile | cut -d , -f 1`

  case $type in
    "BitTorrent file" )
      mv ${tmpfile} ~/downloads/`basename ${tmpfile}`.torrent
      echo "OK :)"
    ;;
    "gzip compressed data" )
      mv ${tmpfile} ${tmpfile}.gz
      gunzip ${tmpfile}.gz
      mv ${tmpfile} ~/downloads/`basename ${tmpfile}`.torrent
      echo "compressed, still OK :)"
    ;;
    "ASCII text" )
      echo "Ascii, select other link"
    ;;
    * )
      echo "Unknown type: ${type}"
    ;;
  esac

}

echo "Waiting for torrent url..."

while read input; do

  if [[ "${input}" =~ "magnet:" ]]
  then
    magnet "${input}"
  else
    torrent "${input}"
  fi

done
